### ISSUE TITLE
Attempting to save a dynamic attribute with a null value results in a NullPointerException

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/ecodata#565]
When passing in dateTaken dynamic attribute null, update properties in CommonService fails when calling save

![image](https://user-images.githubusercontent.com/1606595/67449665-9cd7db80-f666-11e9-8a83-ed722654317d.png)

![image](https://user-images.githubusercontent.com/1606595/67449571-57b3a980-f666-11e9-9e4a-65f4e6ca8521.png)

dateTaken will have to be mapped to Date in the Document domain class.
Script to update all existing dateTaken to Date type in mongo for retrieval

**Comment by chrisala** [comment]
This was resolved with #565
