### ISSUE TITLE
Duplicate data resources are created on Collectory for bioCollect and MERIT

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/ecodata#567]
Having a look at the data provider's page for bioCollect and MERIT you can see a lot of duplicate data resources assigned to them:
https://collections.ala.org.au/public/show/dp3903
https://collections.ala.org.au/public/show/dp5159

**Comment by matilda2812** [comment]
A data resource is created for projects which don't intend to use BioCollect for collecting data. A data resource should probably only be created if the project will harvest to the ALA.
All projects created after 2018-07-02 have a data resource id stored with the project and don't have multiple data resources in the collectory. 
Currently, updating a project in BioCollect triggers `updateDataResource` in ecodata but this doesn't create a data resource or update the data resource id in the database.

**Comment by sadeghim** [comment]
list of data resources coming from ecodata is here:

dataResourceId | dataProviderId
-- | --
dr3147 | dp1825
dr3372 | dp2057
dr3392 | dp2077
dr5017 | dp3534
dr5018 | dp3535
dr5199 | dp3681
dr5304 | dp3764
dr5329 | dp3777
dr5467 | dp3863
dr364 | dp3874
dr10368 | dp3903
dr13540 | dp3903
dr13802 | dp3903
dr14192 | dp3903
dr14193 | dp3903
dr9095 | dp3903
dr5829 | dp4142
dr2696 | dp429
dr6463 | dp4731
dr6699 | dp4858
dr6975 | dp5002
dr7200 | dp5004
dr7577 | dp5142

It seems that some of them are created way before than this API created and the dataProvider is not updated. 
As per our discussion, to keep the data resources trimmed I wanted to create a script to delete data resources which are not associated with bioCollect as their data provider. But cannot do that now, it will delete some of the above dataResources.

**Comment by temi** [comment]
Updated code to create data resource only for projects sharing data with ALA. And, fixed bug which created multiple DRs.
CR: https://upsource.ala.org.au/ecodata/review/ECDT-CR-10
