### ISSUE TITLE
Change mapping of basisOfRecord

### ISSUE THREAD

**Issue by matilda2812** [AtlasOfLivingAustralia/ecodata#580]
Currently basisOfRecord is `HumanObservation` for all records. For certain survey types, this should be `MachineObservation`. 

Need a check on survey type to distinguish between survey types. The survey types (`methodType` attribute) that should be `MachineObservation` are: 
Bat survey - Echolocation recorder
Fauna survey - Camera trapping

**Comment by temi** [comment]
@matilda2812 , not able to get this to work. Can you create a record on biocollect-dev with the correct configuration so that this can be tested?
