### ISSUE TITLE
Error updating project associated organisations

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/ecodata#708]
To reproduce:
1. Use biocollect to edit a project.
2. Add an associated organsation
3. Save.

Expected:
The project saves.

Actual:
An error is thrown "Value ... is not a valid type for association ..."

**Comment by chrisala** [comment]
https://upsource.ala.org.au/ecodata/review/ECDT-CR-102

**Comment by chrisala** [comment]
https://upsource.ala.org.au/ecodata/review/ECDT-CR-104

**Comment by temi** [comment]
Tested. Passed.
