### ISSUE TITLE
T/F are no longer match terms in boolean fields in elasticsearch

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/ecodata#709]
Due to the elasticsearch upgrade, the values T/F no longer match when applied to boolean fields.
Unfortunately, the Biocollect mobile app sends a query fq=isExternal:F which is now returning no results.

Need to introduce a compatibility layer until we can update the app.

**Comment by chrisala** [comment]
This can be tested using BioCollect running the query:
https://biocollect-test.ala.org.au/ws/project/search?initiator=biocollect&offset=0&max=50&q=&mobile=true&hub=&fq=isExternal%3AF&sort=dateCreatedSort

**Comment by chrisala** [comment]
https://upsource.ala.org.au/ecodata/review/ECDT-CR-103

**Comment by temi** [comment]
Tested and working on mobile app.
